CREATE SCHEMA IF NOT EXISTS partnerlinks;

CREATE TABLE partnerlinks.ingestion_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pipeline_name text NOT NULL,
  source text NOT NULL,
  market text NOT NULL,
  status text NOT NULL CHECK (status IN ('running', 'completed', 'failed', 'cancelled')),
  source_observed_at timestamptz,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  records_seen bigint NOT NULL DEFAULT 0 CHECK (records_seen >= 0),
  records_accepted bigint NOT NULL DEFAULT 0 CHECK (records_accepted >= 0),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_summary text,
  CHECK (completed_at IS NULL OR completed_at >= started_at)
);

CREATE TABLE partnerlinks.creators (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tiktok_oecuid text NOT NULL UNIQUE,
  handle text NOT NULL,
  nickname text,
  avatar_url text,
  screener_status text NOT NULL DEFAULT 'active'
    CHECK (screener_status IN ('active', 'excluded', 'inactive')),
  exclusion_reason text,
  first_seen_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (last_seen_at >= first_seen_at),
  CHECK (
    (screener_status = 'excluded' AND exclusion_reason IS NOT NULL)
    OR screener_status <> 'excluded'
  )
);

CREATE INDEX creators_handle_lower_idx
  ON partnerlinks.creators (lower(handle));
CREATE INDEX creators_active_status_idx
  ON partnerlinks.creators (screener_status)
  WHERE screener_status = 'active';

CREATE TABLE partnerlinks.commerce_categories (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  display_name text NOT NULL,
  parent_id smallint REFERENCES partnerlinks.commerce_categories(id) ON DELETE RESTRICT,
  level smallint NOT NULL CHECK (level IN (1, 2)),
  display_order smallint NOT NULL CHECK (display_order >= 0),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (parent_id, display_name),
  CHECK (
    (level = 1 AND parent_id IS NULL)
    OR (level = 2 AND parent_id IS NOT NULL)
  )
);

CREATE INDEX commerce_categories_parent_order_idx
  ON partnerlinks.commerce_categories (parent_id, display_order);

CREATE TABLE partnerlinks.tiktok_commerce_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  market text NOT NULL,
  external_category_id text NOT NULL,
  name text NOT NULL,
  parent_id bigint REFERENCES partnerlinks.tiktok_commerce_categories(id) ON DELETE RESTRICT,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  active boolean NOT NULL DEFAULT true,
  UNIQUE (market, external_category_id),
  CHECK (last_seen_at >= first_seen_at)
);

CREATE INDEX tiktok_categories_parent_idx
  ON partnerlinks.tiktok_commerce_categories (parent_id);

CREATE TABLE partnerlinks.commerce_category_mappings (
  source_category_id bigint NOT NULL
    REFERENCES partnerlinks.tiktok_commerce_categories(id) ON DELETE RESTRICT,
  commerce_category_id smallint NOT NULL
    REFERENCES partnerlinks.commerce_categories(id) ON DELETE RESTRICT,
  mapping_status text NOT NULL CHECK (mapping_status IN ('mapped', 'parent_only', 'manual')),
  mapping_version integer NOT NULL DEFAULT 1 CHECK (mapping_version > 0),
  reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (source_category_id, commerce_category_id)
);

CREATE INDEX category_mappings_commerce_category_idx
  ON partnerlinks.commerce_category_mappings (commerce_category_id);

CREATE TABLE partnerlinks.creator_category_memberships (
  creator_id uuid NOT NULL REFERENCES partnerlinks.creators(id) ON DELETE CASCADE,
  category_id smallint NOT NULL REFERENCES partnerlinks.commerce_categories(id) ON DELETE RESTRICT,
  membership_origin text NOT NULL
    CHECK (membership_origin IN ('mapped', 'inherited_parent', 'parent_only', 'legacy_import', 'manual')),
  mapping_version integer CHECK (mapping_version IS NULL OR mapping_version > 0),
  first_seen_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL,
  active boolean NOT NULL DEFAULT true,
  PRIMARY KEY (creator_id, category_id),
  CHECK (last_seen_at >= first_seen_at)
);

CREATE INDEX creator_memberships_category_creator_idx
  ON partnerlinks.creator_category_memberships (category_id, creator_id)
  WHERE active = true;
CREATE INDEX creator_memberships_creator_idx
  ON partnerlinks.creator_category_memberships (creator_id)
  WHERE active = true;

CREATE TABLE partnerlinks.creator_metric_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL REFERENCES partnerlinks.creators(id) ON DELETE CASCADE,
  ingestion_run_id uuid NOT NULL REFERENCES partnerlinks.ingestion_runs(id) ON DELETE RESTRICT,
  observed_at timestamptz NOT NULL,
  ingested_at timestamptz NOT NULL DEFAULT now(),
  source_metric_period text NOT NULL,
  source_metric_period_days smallint CHECK (source_metric_period_days IS NULL OR source_metric_period_days > 0),
  currency_code char(3) NOT NULL DEFAULT 'USD',
  med_gmv_revenue numeric(20,2) CHECK (med_gmv_revenue IS NULL OR med_gmv_revenue >= 0),
  med_gmv_revenue_range_label text,
  med_gmv_revenue_range_lower numeric(20,2)
    CHECK (med_gmv_revenue_range_lower IS NULL OR med_gmv_revenue_range_lower >= 0),
  med_gmv_revenue_range_upper numeric(20,2)
    CHECK (med_gmv_revenue_range_upper IS NULL OR med_gmv_revenue_range_upper >= 0),
  video_gmv numeric(20,2) CHECK (video_gmv IS NULL OR video_gmv >= 0),
  live_gmv numeric(20,2) CHECK (live_gmv IS NULL OR live_gmv >= 0),
  followers bigint CHECK (followers IS NULL OR followers >= 0),
  units_sold bigint CHECK (units_sold IS NULL OR units_sold >= 0),
  units_sold_range_label text,
  units_sold_range_lower bigint CHECK (units_sold_range_lower IS NULL OR units_sold_range_lower >= 0),
  units_sold_range_upper bigint CHECK (units_sold_range_upper IS NULL OR units_sold_range_upper >= 0),
  audience_dominant_gender text
    CHECK (audience_dominant_gender IS NULL OR audience_dominant_gender IN ('Female', 'Male')),
  audience_dominant_percentage numeric(5,2)
    CHECK (audience_dominant_percentage IS NULL OR audience_dominant_percentage BETWEEN 0 AND 100),
  source_record_hash text,
  UNIQUE (creator_id, observed_at, source_metric_period),
  UNIQUE (id, creator_id),
  CHECK (
    med_gmv_revenue_range_upper IS NULL
    OR med_gmv_revenue_range_lower IS NULL
    OR med_gmv_revenue_range_upper >= med_gmv_revenue_range_lower
  ),
  CHECK (
    units_sold_range_upper IS NULL
    OR units_sold_range_lower IS NULL
    OR units_sold_range_upper >= units_sold_range_lower
  )
);

CREATE INDEX creator_snapshots_history_idx
  ON partnerlinks.creator_metric_snapshots (creator_id, observed_at DESC);
CREATE INDEX creator_snapshots_cohort_gmv_idx
  ON partnerlinks.creator_metric_snapshots (observed_at, med_gmv_revenue DESC, creator_id);
CREATE INDEX creator_snapshots_ingestion_run_idx
  ON partnerlinks.creator_metric_snapshots (ingestion_run_id);

CREATE TABLE partnerlinks.creator_current_metrics (
  creator_id uuid PRIMARY KEY REFERENCES partnerlinks.creators(id) ON DELETE CASCADE,
  snapshot_id uuid NOT NULL UNIQUE,
  observed_at timestamptz NOT NULL,
  source_metric_period text NOT NULL,
  source_metric_period_days smallint CHECK (source_metric_period_days IS NULL OR source_metric_period_days > 0),
  currency_code char(3) NOT NULL DEFAULT 'USD',
  med_gmv_revenue numeric(20,2) CHECK (med_gmv_revenue IS NULL OR med_gmv_revenue >= 0),
  med_gmv_revenue_range_label text,
  med_gmv_revenue_range_lower numeric(20,2)
    CHECK (med_gmv_revenue_range_lower IS NULL OR med_gmv_revenue_range_lower >= 0),
  med_gmv_revenue_range_upper numeric(20,2)
    CHECK (med_gmv_revenue_range_upper IS NULL OR med_gmv_revenue_range_upper >= 0),
  ranking_gmv_value numeric(20,2)
    GENERATED ALWAYS AS (COALESCE(med_gmv_revenue, med_gmv_revenue_range_lower)) STORED,
  gmv_is_exact boolean GENERATED ALWAYS AS (med_gmv_revenue IS NOT NULL) STORED,
  video_gmv numeric(20,2) CHECK (video_gmv IS NULL OR video_gmv >= 0),
  live_gmv numeric(20,2) CHECK (live_gmv IS NULL OR live_gmv >= 0),
  followers bigint CHECK (followers IS NULL OR followers >= 0),
  units_sold bigint CHECK (units_sold IS NULL OR units_sold >= 0),
  units_sold_range_label text,
  units_sold_range_lower bigint CHECK (units_sold_range_lower IS NULL OR units_sold_range_lower >= 0),
  units_sold_range_upper bigint CHECK (units_sold_range_upper IS NULL OR units_sold_range_upper >= 0),
  audience_dominant_gender text
    CHECK (audience_dominant_gender IS NULL OR audience_dominant_gender IN ('Female', 'Male')),
  audience_dominant_percentage numeric(5,2)
    CHECK (audience_dominant_percentage IS NULL OR audience_dominant_percentage BETWEEN 0 AND 100),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (snapshot_id, creator_id)
    REFERENCES partnerlinks.creator_metric_snapshots(id, creator_id) ON DELETE RESTRICT,
  CHECK (
    med_gmv_revenue_range_upper IS NULL
    OR med_gmv_revenue_range_lower IS NULL
    OR med_gmv_revenue_range_upper >= med_gmv_revenue_range_lower
  ),
  CHECK (
    units_sold_range_upper IS NULL
    OR units_sold_range_lower IS NULL
    OR units_sold_range_upper >= units_sold_range_lower
  )
);

CREATE INDEX creator_current_gmv_rank_idx
  ON partnerlinks.creator_current_metrics (ranking_gmv_value DESC, creator_id);
CREATE INDEX creator_current_followers_idx
  ON partnerlinks.creator_current_metrics (followers DESC, creator_id);

CREATE TABLE partnerlinks.creator_discoveries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingestion_run_id uuid NOT NULL REFERENCES partnerlinks.ingestion_runs(id) ON DELETE RESTRICT,
  creator_id uuid NOT NULL REFERENCES partnerlinks.creators(id) ON DELETE CASCADE,
  source_category_id bigint REFERENCES partnerlinks.tiktok_commerce_categories(id) ON DELETE RESTRICT,
  search_query text,
  discovery_key text NOT NULL,
  page_number integer CHECK (page_number IS NULL OR page_number >= 0),
  result_position integer CHECK (result_position IS NULL OR result_position >= 0),
  discovered_at timestamptz NOT NULL,
  UNIQUE (ingestion_run_id, creator_id, discovery_key)
);

CREATE INDEX creator_discoveries_creator_idx
  ON partnerlinks.creator_discoveries (creator_id, discovered_at DESC);
CREATE INDEX creator_discoveries_category_idx
  ON partnerlinks.creator_discoveries (source_category_id, discovered_at DESC)
  WHERE source_category_id IS NOT NULL;

COMMENT ON COLUMN partnerlinks.creator_metric_snapshots.source_metric_period IS
  'Source-validated metric period semantics. Do not infer a period from UI labels.';
COMMENT ON COLUMN partnerlinks.creator_metric_snapshots.source_metric_period_days IS
  'Populated only when the source period has been explicitly validated.';
COMMENT ON COLUMN partnerlinks.creator_current_metrics.ranking_gmv_value IS
  'Exact med_gmv_revenue when available, otherwise the preserved range lower bound.';
