export type HeatmapMarket = { name: string; buckets: readonly string[] };

// UGCWEB Market Architecture — Master V1, Parent Markets + Locked Buckets.
export const heatmapMarkets: readonly HeatmapMarket[] = [
  { name: "Sports & Outdoors", buckets: ["Golf", "Pickleball", "Tennis", "Basketball", "Football", "Baseball & Softball", "Soccer", "Volleyball", "Running & Track", "Cycling", "Swimming", "Boxing & MMA", "Wrestling", "Gymnastics", "Hockey", "Skateboarding", "Surfing", "Disc Golf", "Fitness & Gym", "Yoga & Pilates", "Camping & Hiking", "Fishing", "Hunting", "Water Sports", "Winter Sports"] },
  { name: "Fashion & Apparel", buckets: ["Dresses", "Tops & Shirts", "Pants & Trousers", "Jeans & Denim", "Shorts", "Skirts", "Activewear", "Loungewear", "Sleepwear", "Outerwear", "Swimwear", "Underwear & Lingerie", "Shapewear", "Suits & Formalwear", "Matching Sets", "Costumes", "Shoes & Footwear", "Socks & Hosiery"] },
  { name: "Beauty & Personal Care", buckets: ["Skincare", "Body Care", "Haircare", "Hair Styling", "Hair Color", "Wigs & Hair Extensions", "Makeup & Cosmetics", "Nails & Nail Art", "Fragrance & Perfume", "Deodorants & Antiperspirants", "Bath & Shower", "Shaving & Hair Removal", "Oral Care", "Beauty Tools & Devices", "Personal Hygiene", "Tanning & Sun Care"] },
  { name: "Food & Beverage", buckets: ["Snacks", "Candy & Chocolate", "Nuts & Dried Fruit", "Protein Bars & Snacks", "Coffee", "Tea & Matcha", "Energy & Sports Drinks", "Juices & Smoothies", "Soda & Soft Drinks", "Water & Sparkling Water", "Drink Mixes & Powders", "Breakfast Foods", "Baking & Desserts", "Pantry Staples", "Sauces & Condiments", "Spices & Seasonings", "Instant & Ready-to-Eat Meals", "International Foods", "Specialty & Gourmet Foods"] },
  { name: "Home & Living", buckets: ["Furniture", "Home Decor", "Kitchen & Dining", "Bedding", "Bathroom", "Cleaning", "Laundry", "Storage & Organization", "Lighting", "Household Appliances", "Home Fragrance", "Rugs & Curtains", "Lawn & Garden", "Outdoor Living", "Seasonal & Holiday Decor"] },
  { name: "Pets", buckets: ["Pet Food & Treats", "Pet Supplements & Wellness", "Pet Toys", "Pet Beds & Furniture", "Pet Clothing & Accessories", "Collars, Leashes & Harnesses", "Pet Grooming & Hygiene", "Pet Training", "Pet Bowls & Feeders", "Pet Carriers & Travel", "Aquariums & Fish Supplies", "Bird Supplies", "Small Animal Supplies", "Reptile & Amphibian Supplies", "Pet Tech & Smart Devices", "Pet Safety & Containment"] },
  { name: "Electronics & Tech", buckets: ["Smartphones & Mobile Devices", "Phone Cases & Accessories", "Computers & Laptops", "Computer Accessories & Peripherals", "PC Components & Hardware", "Gaming Consoles & Accessories", "Audio Equipment", "Cameras & Creator Equipment", "Smartwatches & Wearables", "Smart Home Devices", "Home Security & Surveillance", "Networking & Wi-Fi", "TVs & Home Entertainment", "Monitors & Displays", "Charging & Connectivity", "Drones & Remote-Control Tech", "3D Printers & Accessories"] },
  { name: "Automotive & Motorcycle", buckets: ["Car Interior & Organization", "Car Exterior Accessories", "Car Cleaning & Detailing", "Car Electronics & Audio", "Vehicle Lighting", "Car Performance & Tuning", "Auto Replacement Parts", "Tires & Wheels", "Car Maintenance & Fluids", "Car Tools & Diagnostics", "Car Safety & Emergency Equipment", "Truck & SUV Accessories", "Motorcycle Parts & Maintenance", "Motorcycle Riding Gear", "ATV & UTV Accessories", "RV & Camper Accessories", "Electric Vehicle Accessories"] },
  { name: "Health & Wellness", buckets: ["Vitamins & Supplements", "Sports Nutrition & Performance", "Weight Management", "Digestive & Gut Health", "Sleep, Stress & Relaxation", "Immune Support", "Women's Health", "Men's Health", "Joint & Bone Health", "Heart & Circulation Health", "Brain & Cognitive Support", "Pain Relief & Recovery", "Massage & Recovery Devices", "First Aid & Medical Supplies", "Mobility & Accessibility Aids", "Health Monitoring Devices"] },
  { name: "Baby & Kids", buckets: ["Baby Clothing", "Kids' Clothing", "Baby & Kids' Footwear", "Baby Accessories", "Diapers & Wipes", "Baby Bath & Skincare", "Baby Feeding & Nursing", "Baby Food & Formula", "Pacifiers & Teethers", "Baby Travel & Carriers", "Car Seats & Baby Safety", "Nursery & Baby Sleep", "Baby Monitors & Tech", "Potty Training", "Maternity & Postpartum", "Kids' School Supplies", "Baby & Toddler Development"] },
  { name: "Toys & Collectibles", buckets: ["Figures & Figurines", "Dolls & Doll Accessories", "Plush Toys & Stuffed Animals", "Building Blocks & Construction Toys", "Educational & STEM Toys", "Board Games", "Card Games & Trading Cards", "Puzzles & Brain Teasers", "Remote-Control Toys", "Models & Miniatures", "Blind Boxes & Mystery Collectibles", "Anime & Pop Culture Collectibles", "Sports Collectibles & Memorabilia", "Outdoor Toys & Play Equipment", "Pretend Play & Roleplay Toys", "Fidget & Sensory Toys", "Arts & Crafts Kits"] },
  { name: "Jewelry & Accessories", buckets: ["Necklaces", "Bracelets", "Rings", "Earrings", "Watches", "Anklets & Body Jewelry", "Handbags", "Wallets", "Eyewear", "Headwear", "Hair Accessories", "Belts"] },
  { name: "Tools & Home Improvement", buckets: ["Power Tools", "Hand Tools & Tool Kits", "Tool Accessories & Attachments", "Measuring & Layout Tools", "Hardware & Repair Supplies", "Electrical Supplies", "Plumbing Supplies", "Painting Supplies & Equipment", "Building Materials", "Flooring & Tiling", "Doors, Windows & Hardware", "Ladders & Scaffolding", "Workshop Equipment", "Tool Storage & Organization", "Safety & Protective Equipment", "Lawn & Garden Tools", "Welding & Soldering Equipment"] },
  { name: "Travel & Luggage", buckets: ["Luggage & Suitcases", "Backpacks", "Duffel & Weekender Bags", "Travel Accessories", "Packing & Organization", "Travel Comfort", "Travel Tech", "Travel Safety & Security", "Travel Bags & Organizers", "Kids' Travel Gear"] },
  { name: "Books & Entertainment", buckets: ["Fiction Books", "Nonfiction Books", "Children's Books", "Educational & Academic Books", "Self-Help & Personal Development", "Religious & Spiritual Books", "Comics, Manga & Graphic Novels", "Coloring & Activity Books", "Stationery, Journals & Planners", "Arts & Crafts Supplies", "Music & Vinyl Records", "Movies & Physical Media"] },
] as const;

export function heatmapSlug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

export function heatmapScopeForSlug(slug: string) {
  for (const market of heatmapMarkets) {
    if (heatmapSlug(market.name) === slug) return { market, name: market.name, kind: "market" as const };
    const bucket = market.buckets.find((item) => heatmapSlug(item) === slug);
    if (bucket) return { market, name: bucket, kind: "bucket" as const };
  }
  return null;
}
